version: '3.1'

volumes:
  jenkinsdata:
  jenkinsconf:

networks:
  nw001:

services:
  jenkinsmaster:
    build: jenkins-master
    image: michaellihs/jenkins
    ports:
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkinsdata:/var/log/jenkins
      - jenkinsconf:/var/jenkins_home
    networks:
      nw001:
        aliases:
          - jenkins-master

  jenkinsnginx:
    build: jenkins-nginx
    image: michaellihs/jenkinsnginx
    ports:
      - 8081:8081
    networks:
      - nw001

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
